name: Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > private_key
        chmod 600 private_key

    - name: Deploy to server
      run: |
        rsync -r --delete-after --quiet -e 'ssh -i private_key' ${{ github.workspace }} emohawk13@dauhsoncapps.info:/var/www/html/
        ssh -i private_key emohawk13@dauhsoncapps.info "cd /var/www/html/ && ./deploy_script.sh"

